(cl:defpackage lidar_localization-srv
  (:use )
  (:export
   "OPTIMIZEMAP"
   "<OPTIMIZEMAP-REQUEST>"
   "OPTIMIZEMAP-REQUEST"
   "<OPTIMIZEMAP-RESPONSE>"
   "OPTIMIZEMAP-RESPONSE"
   "SAVEMAP"
   "<SAVEMAP-REQUEST>"
   "SAVEMAP-REQUEST"
   "<SAVEMAP-RESPONSE>"
   "SAVEMAP-RESPONSE"
   "SAVESCANCONTEXT"
   "<SAVESCANCONTEXT-REQUEST>"
   "SAVESCANCONTEXT-REQUEST"
   "<SAVESCANCONTEXT-RESPONSE>"
   "SAVESCANCONTEXT-RESPONSE"
  ))

